<!DOCTYPE html>
<html lang="cs">
  <head> 
    <!--<style>@import url("css/style.css");</style>-->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="css/table.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    
    <script type="text/javascript" src="ckeditor/ckeditor.js"></script>
    <link rel="shortcut icon" href="icon/icon.ico" >
    
    <div class="container-fluid">
    <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="index.php">WebKonference</a>
      </div>
       <ul class="nav navbar-nav">
        <li><a href="index.php?page=konf">Nástěnka</a></li>
        <li><a href="index.php?page=cont">Příspěvky</a></li>
        <?php if($_SESSION['privileges']==1) { ?>
        <li><a href="index.php?page=user_edit">Uživatelé</a></li>
        <?php } ?>
      </ul>
      <?php
        if ($_SESSION['signed']==false) {
          echo '
            <ul class="nav navbar-nav navbar-right">
            <li><a href="index.php?page=login"><span class="glyphicon glyphicon-log-in"></span> Přihlásit se</a></li>
            <li><a href="index.php?page=signUp"><span class="glyphicon glyphicon-pencil"></span> Zaregistrovat se</a></li>
            </ul>
          ';
        }
        else {
          $user = $_SESSION['user'];
          echo '
            <ul class="nav navbar-nav navbar-right">
            <li><a href="index.php?page=konf">uživatel: '. $user .'</a></li>
              <li><a href="index.php?page=signOut"><span class="glyphicon glyphicon-log-out"></span> Odhlásit se</a></li>
              </ul>
            ';
          }
        ?>
        
      </div>
    </nav>
    <?php
       require ("view/$this->view.phtml"); //zavolání pohledu, nastavuje se v daném kontroleru
    ?>
    <footer><p align ="right">Copyright &copy; Vaněk Jakub</p></footer>
   </div>

  </body>
</html>