
<h2>Seznam příspěvků</h2>
<br>
<div class="container">
				  <table class="table table-bordered table-striped">
				    <thead class="thead-inverse">
                        <tr>
                            <th rowspan="2">Název</th>
                            <th rowspan="2">Autoři</th>
                            <th colspan="6">Recenze</th>
                            <th rowspan="2">Rozhodnutí</th>
                        </tr>

                        <tr class = "subCol">
                              <th>Recenzent</th>
                              <th> ORIG.</th>
                              <th>KVAL.</th>
                              <th>DOPO.</th>
                              <th>CELK.</th>
                              <th>VYMAZAT</th>
                        </tr>
                        </thead>
				    <tbody> 
				      <?php echo $_POST['tableBody']; 

				      ?>
				    </tbody>
				  </table>
				</div>


