<h2>Upravit příspěvek</h2>
<form action ="" class="" method="post">
	<div class="form-group col-xs-12">
		<div class="form-group col-xs-5">
	  		<div class="form-group">
	  			<label>Název příspěvku</label>
	    		<input name="contName" type="text" class="form-control" required="" autofocus="" value="<?php echo $this->contName;?>">
	  		</div>
		</div>
		<div class="form-group col-xs-8">
	  			<label>příspěvek</label>
	    		<textarea name="cont" class="form-control" id="exampleTextarea" rows="5" required="" ><?php echo $this->cont;?></textarea>
	  	</div>
	  	<div class="form-group col-xs-11">
			<button name="editContButton" type="submit" class="btn btn-primary">Upravit příspěvek</button>
			<button name="back"  class="btn btn-primary" formnovalidate>Zpět</button>
		</div>
	</div>
</form>