<head>
  <title>Konference_Login</title>
  <link rel="stylesheet" type="text/css" href="css/login.css">
</head>
<body> 
  <div class="container-fluid">

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="index.php">WebKonference</a>
    </div>
     <ul class="nav navbar-nav">
      <li><a href="index.php">Zpět</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="index.php?page=login"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
    </ul>
  </div>
</nav>
             
  <div class="wrapper">
    <form class="form-signin">       
      <h2 class="form-signin-heading">Přihlásit se</h2>
      <input type="text" class="form-control" name="username" placeholder="e-mail" required="" autofocus="" />
      <input type="password" class="form-control" name="password" placeholder="Heslo" required=""/> 
      <button class="btn btn-lg btn-primary btn-block" type="submit">Přihlásit</button>
      
    </form>
  </div>