<h2>Nový příspěvek</h2>
<form action ="" class="" method="post">
	<div class="form-group col-xs-12">
		<div class="form-group col-xs-5">
	  		<div class="form-group">
	  			<label>Název příspěvku</label>
	    		<input name="contName" type="text" class="form-control" required="" autofocus="">
	  		</div>
		</div>
		<div class="form-group col-xs-8">
	  			<label>příspěvek</label>
	    		<textarea name="cont" class="form-control" id="exampleTextarea" rows="5" required=""></textarea>
	  	</div>
	  	<div class="form-group col-xs-11">
			<button name="addNewContButton" type="submit" class="btn btn-primary">Přidat příspěvek</button>
			<button name="back"  class="btn btn-primary" formnovalidate>Zpět</button>
		</div>
	</div>
</form>