<h2>Nový příspěvek</h2>
<form action ="" class="" method="post" enctype="multipart/form-data">
	<div class="form-group col-xs-12">
		<div class="row">
			<div class="form-group col-xs-5">
		  		<div class="form-group">
		  			<label>Název příspěvku</label>
		    		<input name="contName" type="text" class="form-control" required="" autofocus="">
		  		</div>
			</div>
		</div>
		<div class="row">
			<div class="form-group col-xs-6">
		  			<label>příspěvek</label>
		    		<textarea name="cont" class="form-control" id="exampleTextarea" rows="5" required=""></textarea>
		  	</div>
		</div>
		<div class="row">
		  	<div class="form-group col-xs-6">
		  		<div class="form-group">
				   <label for="file">Nahrajte soubor</label>
				   <input type="file" name="file" accept>
				</div>
			</div>
		</div>
		<div class="row">
		  	<div class="form-group col-xs-11">
				<button name="addNewContButton" type="submit" class="btn btn-primary">Přidat příspěvek</button>
				<button name="back"  class="btn btn-primary" formnovalidate>Zpět</button>
			</div>
		</div>
	</div>
</form>