
<h2>Příspěvky k ohodnocení</h2>
<?php
	if($_POST['revs']==NULL){
		echo '<h3> Žádné příspěvky </h3>';
	} else { ?>
<table class="table table-bordered table-striped">
    <thead class="thead-inverse">
        <tr>
			<th>Název</th>
			<th>Autor</th>
			<th>Orig.</th>
			<th>Kval.</th>
			<th>Dopo.</th>
			<th>Celk.</th>
			<th>Akce</th>
		</tr>
	</thead>
	<tbody>
		<?php
			foreach ($_POST['revs'] as $record) { 
				$tmp = Database::getCont($record['cont_id']);
				$cont = array_shift($tmp);
		?>
		<tr>
			<td>
				<?php
					echo $cont['name'];
				?> 
			</td>
			<td>
				<?php
					echo $cont['author'];
				?> 
			</td>

			<td>
				<?php
					echo $record['originality'];
				?> 
			</td>
			<td>
				<?php
					echo $record['quality'];
				?> 
			</td>
			<td>
				<?php
					echo $record['recommendation'];
				?> 
			</td>
			<td>
				<?php
					echo $record['overall'];
				?> 
			</td>
			<td>
				<form method='post'>
					<?php if($cont['decision']==0) {?>
					<button name='reviewButton' type='submit' class='btn btn-default btn-info btn-sm' value='<?php echo $record['id'] ?>'>
						<span class='glyphicon glyphicon glyphicon-edit'></span> Hodnotit příspěvek
					</button>
					<?php } else {  ?>
					<button name='' type='submit' class='btn btn-default btn-warning btn-sm' value='<?php echo $record['id'] ?>'>
						<span class='glyphicon glyphicon glyphicon-warning'></span> Příspěvek nelze dále hodnotit
					</button>
					<?php } ?>

				</form>
			</td>
		</tr>

		<?php
			}
		}
		?>			
	</tbody>	
</table>

