<h2>Upravit uživatele</h2>
<form action ="" class="" method="post">
	<div class="form-group col-xs-12">
		<div class="row">
			<div class="form-group col-xs-5">
		  		<div class="form-group">
		  			<label>Uživatelské jméno</label>
		    		<input name="loginBox" type="text" class="form-control" required="" autofocus="" value="<?php echo $this->login?>">
		  		</div>
			</div>
		</div>
		<div class="row">
			<div class="form-group col-xs-5">
		  		<div class="form-group">
		  			<label>Jméno a příjmení</label>
		    		<input name="nameBox" type="text" class="form-control" required="" autofocus="" value="<?php echo $this->name?>">
		  		</div>
			</div>
		</div>
		<div class="row">
			<div class="form-group col-xs-5">
		  		<div class="form-group">
		  			<label>E-mail</label>
		    		<input name="mailBox" type="text" class="form-control" required="" autofocus="" value="<?php echo $this->email?>">
		  		</div>
			</div>
		</div>
		<div class="row">
			<div class="form-group col-xs-5">
		  		<div class="form-group">
		  			<label>Práva</label>
		  			<select class='form-control' name='privilegesSel' id='sel1'>
		  				<?php 
		    			switch($this->privileges){
							case '1': { ?>
								<option value="1" selected>Administrátor</option>
		  						<option value="2">Recenzent</option>
		  						<option value="3">Autor</option> 
							<?php } 
								break;
							case '2': { ?>
								<option value="1">Administrátor</option>
		  						<option value="2" selected>Recenzent</option>
		  						<option value="3">Autor</option> 
							<?php } 
								break;
							case '3': { ?>
								<option value="1">Administrátor</option>
		  						<option value="2">Recenzent</option>
		  						<option value="3" selected>Autor</option> 
							} <?php
								break;
							} default: {
							?>
								<option value="1">Administrátor</option>
		  						<option value="2">Recenzent</option>
		  						<option value="3">Autor</option> 
							<?php
							}}
							?>

						</option>
		  			</select>
		  		</div>
			</div>
		</div>
		<div class="row">

		</div>
		<div class="row">
		  	<div class="form-group col-xs-11">
				<button name="editUserButton" type="submit" class="btn btn-primary">Upravit uživatele</button>
				<button name="backButton"  class="btn btn-primary" formnovalidate>Zpět</button>
			</div>
		</div>
	</div>
</form>